name: Lock closed issue

on: 
  issues:
    types: [closed]
  workflow_dispatch:

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
    - uses: OSDKDev/lock-issues@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
